/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosUsoRouteImport } from './routes/termos-uso'
import { Route as SupletivoOnlineRouteImport } from './routes/supletivo-online'
import { Route as SupletivoGoianiaRouteImport } from './routes/supletivo-goiania'
import { Route as SupletivoAparecidaDeGoianiaRouteImport } from './routes/supletivo-aparecida-de-goiania'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PoliticaPrivacidadeRouteImport } from './routes/politica-privacidade'
import { Route as MatriculaRouteImport } from './routes/matricula'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EjaOnlineRouteImport } from './routes/eja-online'
import { Route as EjaGoianiaRouteImport } from './routes/eja-goiania'
import { Route as EjaAparecidaDeGoianiaRouteImport } from './routes/eja-aparecida-de-goiania'
import { Route as EjaRouteImport } from './routes/eja'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CursoSlugRouteImport } from './routes/curso.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminEjaRouteImport } from './routes/admin.eja'
import { Route as AdminCursosRouteImport } from './routes/admin.cursos'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminMatriculasRouteImport } from './routes/admin.matriculas'

const TermosUsoRoute = TermosUsoRouteImport.update({
  id: '/termos-uso',
  path: '/termos-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const SupletivoOnlineRoute = SupletivoOnlineRouteImport.update({
  id: '/supletivo-online',
  path: '/supletivo-online',
  getParentRoute: () => rootRouteImport,
} as any)
const SupletivoGoianiaRoute = SupletivoGoianiaRouteImport.update({
  id: '/supletivo-goiania',
  path: '/supletivo-goiania',
  getParentRoute: () => rootRouteImport,
} as any)
const SupletivoAparecidaDeGoianiaRoute =
  SupletivoAparecidaDeGoianiaRouteImport.update({
    id: '/supletivo-aparecida-de-goiania',
    path: '/supletivo-aparecida-de-goiania',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadeRoute = PoliticaPrivacidadeRouteImport.update({
  id: '/politica-privacidade',
  path: '/politica-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MatriculaRoute = MatriculaRouteImport.update({
  id: '/matricula',
  path: '/matricula',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EjaOnlineRoute = EjaOnlineRouteImport.update({
  id: '/eja-online',
  path: '/eja-online',
  getParentRoute: () => rootRouteImport,
} as any)
const EjaGoianiaRoute = EjaGoianiaRouteImport.update({
  id: '/eja-goiania',
  path: '/eja-goiania',
  getParentRoute: () => rootRouteImport,
} as any)
const EjaAparecidaDeGoianiaRoute = EjaAparecidaDeGoianiaRouteImport.update({
  id: '/eja-aparecida-de-goiania',
  path: '/eja-aparecida-de-goiania',
  getParentRoute: () => rootRouteImport,
} as any)
const EjaRoute = EjaRouteImport.update({
  id: '/eja',
  path: '/eja',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CursoSlugRoute = CursoSlugRouteImport.update({
  id: '/curso/$slug',
  path: '/curso/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEjaRoute = AdminEjaRouteImport.update({
  id: '/eja',
  path: '/eja',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCursosRoute = AdminCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatriculasRoute = AdminMatriculasRouteImport.update({
  id: '/matriculas',
  path: '/matriculas',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/contato': typeof ContatoRoute
  '/eja': typeof EjaRoute
  '/eja-aparecida-de-goiania': typeof EjaAparecidaDeGoianiaRoute
  '/eja-goiania': typeof EjaGoianiaRoute
  '/eja-online': typeof EjaOnlineRoute
  '/login': typeof LoginRoute
  '/matricula': typeof MatriculaRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supletivo-aparecida-de-goiania': typeof SupletivoAparecidaDeGoianiaRoute
  '/supletivo-goiania': typeof SupletivoGoianiaRoute
  '/supletivo-online': typeof SupletivoOnlineRoute
  '/termos-uso': typeof TermosUsoRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/eja': typeof AdminEjaRoute
  '/admin/matriculas': typeof AdminMatriculasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/curso/$slug': typeof CursoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/contato': typeof ContatoRoute
  '/eja': typeof EjaRoute
  '/eja-aparecida-de-goiania': typeof EjaAparecidaDeGoianiaRoute
  '/eja-goiania': typeof EjaGoianiaRoute
  '/eja-online': typeof EjaOnlineRoute
  '/login': typeof LoginRoute
  '/matricula': typeof MatriculaRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supletivo-aparecida-de-goiania': typeof SupletivoAparecidaDeGoianiaRoute
  '/supletivo-goiania': typeof SupletivoGoianiaRoute
  '/supletivo-online': typeof SupletivoOnlineRoute
  '/termos-uso': typeof TermosUsoRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/eja': typeof AdminEjaRoute
  '/admin/matriculas': typeof AdminMatriculasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/curso/$slug': typeof CursoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/contato': typeof ContatoRoute
  '/eja': typeof EjaRoute
  '/eja-aparecida-de-goiania': typeof EjaAparecidaDeGoianiaRoute
  '/eja-goiania': typeof EjaGoianiaRoute
  '/eja-online': typeof EjaOnlineRoute
  '/login': typeof LoginRoute
  '/matricula': typeof MatriculaRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supletivo-aparecida-de-goiania': typeof SupletivoAparecidaDeGoianiaRoute
  '/supletivo-goiania': typeof SupletivoGoianiaRoute
  '/supletivo-online': typeof SupletivoOnlineRoute
  '/termos-uso': typeof TermosUsoRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/eja': typeof AdminEjaRoute
  '/admin/matriculas': typeof AdminMatriculasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/curso/$slug': typeof CursoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/contato'
    | '/eja'
    | '/eja-aparecida-de-goiania'
    | '/eja-goiania'
    | '/eja-online'
    | '/login'
    | '/matricula'
    | '/politica-privacidade'
    | '/quem-somos'
    | '/sitemap.xml'
    | '/supletivo-aparecida-de-goiania'
    | '/supletivo-goiania'
    | '/supletivo-online'
    | '/termos-uso'
    | '/admin/blog'
    | '/admin/categorias'
    | '/admin/cursos'
    | '/admin/eja'
    | '/admin/matriculas'
    | '/blog/$slug'
    | '/categoria/$slug'
    | '/curso/$slug'
    | '/admin/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/contato'
    | '/eja'
    | '/eja-aparecida-de-goiania'
    | '/eja-goiania'
    | '/eja-online'
    | '/login'
    | '/matricula'
    | '/politica-privacidade'
    | '/quem-somos'
    | '/sitemap.xml'
    | '/supletivo-aparecida-de-goiania'
    | '/supletivo-goiania'
    | '/supletivo-online'
    | '/termos-uso'
    | '/admin/blog'
    | '/admin/categorias'
    | '/admin/cursos'
    | '/admin/eja'
    | '/admin/matriculas'
    | '/blog/$slug'
    | '/categoria/$slug'
    | '/curso/$slug'
    | '/admin'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogo'
    | '/contato'
    | '/eja'
    | '/eja-aparecida-de-goiania'
    | '/eja-goiania'
    | '/eja-online'
    | '/login'
    | '/matricula'
    | '/politica-privacidade'
    | '/quem-somos'
    | '/sitemap.xml'
    | '/supletivo-aparecida-de-goiania'
    | '/supletivo-goiania'
    | '/supletivo-online'
    | '/termos-uso'
    | '/admin/blog'
    | '/admin/categorias'
    | '/admin/cursos'
    | '/admin/eja'
    | '/admin/matriculas'
    | '/blog/$slug'
    | '/categoria/$slug'
    | '/curso/$slug'
    | '/admin/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  ContatoRoute: typeof ContatoRoute
  EjaRoute: typeof EjaRoute
  EjaAparecidaDeGoianiaRoute: typeof EjaAparecidaDeGoianiaRoute
  EjaGoianiaRoute: typeof EjaGoianiaRoute
  EjaOnlineRoute: typeof EjaOnlineRoute
  LoginRoute: typeof LoginRoute
  MatriculaRoute: typeof MatriculaRoute
  PoliticaPrivacidadeRoute: typeof PoliticaPrivacidadeRoute
  QuemSomosRoute: typeof QuemSomosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupletivoAparecidaDeGoianiaRoute: typeof SupletivoAparecidaDeGoianiaRoute
  SupletivoGoianiaRoute: typeof SupletivoGoianiaRoute
  SupletivoOnlineRoute: typeof SupletivoOnlineRoute
  TermosUsoRoute: typeof TermosUsoRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  CursoSlugRoute: typeof CursoSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-uso': {
      id: '/termos-uso'
      path: '/termos-uso'
      fullPath: '/termos-uso'
      preLoaderRoute: typeof TermosUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supletivo-online': {
      id: '/supletivo-online'
      path: '/supletivo-online'
      fullPath: '/supletivo-online'
      preLoaderRoute: typeof SupletivoOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supletivo-goiania': {
      id: '/supletivo-goiania'
      path: '/supletivo-goiania'
      fullPath: '/supletivo-goiania'
      preLoaderRoute: typeof SupletivoGoianiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supletivo-aparecida-de-goiania': {
      id: '/supletivo-aparecida-de-goiania'
      path: '/supletivo-aparecida-de-goiania'
      fullPath: '/supletivo-aparecida-de-goiania'
      preLoaderRoute: typeof SupletivoAparecidaDeGoianiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidade': {
      id: '/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof PoliticaPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matricula': {
      id: '/matricula'
      path: '/matricula'
      fullPath: '/matricula'
      preLoaderRoute: typeof MatriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eja-online': {
      id: '/eja-online'
      path: '/eja-online'
      fullPath: '/eja-online'
      preLoaderRoute: typeof EjaOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eja-goiania': {
      id: '/eja-goiania'
      path: '/eja-goiania'
      fullPath: '/eja-goiania'
      preLoaderRoute: typeof EjaGoianiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eja-aparecida-de-goiania': {
      id: '/eja-aparecida-de-goiania'
      path: '/eja-aparecida-de-goiania'
      fullPath: '/eja-aparecida-de-goiania'
      preLoaderRoute: typeof EjaAparecidaDeGoianiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eja': {
      id: '/eja'
      path: '/eja'
      fullPath: '/eja'
      preLoaderRoute: typeof EjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/curso/$slug': {
      id: '/curso/$slug'
      path: '/curso/$slug'
      fullPath: '/curso/$slug'
      preLoaderRoute: typeof CursoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eja': {
      id: '/admin/eja'
      path: '/eja'
      fullPath: '/admin/eja'
      preLoaderRoute: typeof AdminEjaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cursos': {
      id: '/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AdminCursosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matriculas': {
      id: '/admin/matriculas'
      path: '/matriculas'
      fullPath: '/admin/matriculas'
      preLoaderRoute: typeof AdminMatriculasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminCursosRoute: typeof AdminCursosRoute
  AdminEjaRoute: typeof AdminEjaRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMatriculasRoute: typeof AdminMatriculasRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminCursosRoute: AdminCursosRoute,
  AdminEjaRoute: AdminEjaRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMatriculasRoute: AdminMatriculasRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  ContatoRoute: ContatoRoute,
  EjaRoute: EjaRoute,
  EjaAparecidaDeGoianiaRoute: EjaAparecidaDeGoianiaRoute,
  EjaGoianiaRoute: EjaGoianiaRoute,
  EjaOnlineRoute: EjaOnlineRoute,
  LoginRoute: LoginRoute,
  MatriculaRoute: MatriculaRoute,
  PoliticaPrivacidadeRoute: PoliticaPrivacidadeRoute,
  QuemSomosRoute: QuemSomosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupletivoAparecidaDeGoianiaRoute: SupletivoAparecidaDeGoianiaRoute,
  SupletivoGoianiaRoute: SupletivoGoianiaRoute,
  SupletivoOnlineRoute: SupletivoOnlineRoute,
  TermosUsoRoute: TermosUsoRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  CursoSlugRoute: CursoSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
